# addons/clusters/azure/dev-chris/flux-system/kustomization-customer.yaml

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: planets-and-plans
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./addons/clusters/azure/dev-chris
  prune: true
  sourceRef:
    kind: GitRepository
    name: planets-and-plans
---
# stack Kustomization in cluster
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./addons/base-apps/external-secrets
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets
      namespace: external-secrets
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets-webhook
      namespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: mattermost-byoc-infra
---

