# addons/clusters/azure/dev-chris/flux-system/kustomization-customer.yaml

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-chris
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./addons/clusters/azure/dev-chris
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-config
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: base-config
  path: ./addons/apps/velero
  prune: true
