# addons/clusters/azure/dev-chris/flux-system/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
resources:
  - gotk-components.yaml
  - gitrepository.yaml
  - kustomization-base.yaml
  - kustomization-customer.yaml
