apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../addons/base-apps/wrapper-platform

configMapGenerator:
  - name: wrapper-values
    namespace: flux-system
    behavior: merge
    files:
      - values.yaml=../../values.yaml

patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: wrapper-platform

generatorOptions:
  disableNameSuffixHash: true
