# addons/clusters/azure/dev-chris/apps/wrapper-platform/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml # NOT the base chart folder

configMapGenerator:
  - name: wrapper-values
    namespace: flux-system
    # behavior: merge
    files:
      - values.yaml=../../values.yaml

# patches:
#   - path: helmrelease-patches.yaml
#     target:
#       kind: HelmRelease
#       name: wrapper-platform

generatorOptions:
  disableNameSuffixHash: true
