# addons/clusters/azure/dev-chris/apps/velero/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../base-apps/velero

configMapGenerator:
  - name: velero-values
    namespace: velero
    files:
      - values.yaml=../../values.yaml

patches:
  - path: helmrelease-patches.yaml
    target:
      kind: HelmRelease
      name: velero

generatorOptions:
  disableNameSuffixHash: true
