# addons/clusters/azure/dev-chris/apps/external-secrets/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# resources:
#   - base
#   - stack

resources:
  - ../../../../../apps/envoy-gateway

patches:
  - path: patches.yaml
