apiVersion: v1
kind: Service
metadata:
  name: mattermost-lb
  namespace: mattermost
spec:
  type: LoadBalancer
  selector:
    app: mattermost
    installation.mattermost.com/installation: mattermost
    installation.mattermost.com/resource: mattermost
  ports:
    - name: http
      protocol: TCP
      port: 443
      targetPort: 8065
