apiVersion: v1
kind: Service
metadata:
  name: mattermost-lb
  namespace: mattermost
  annotations:
    # Terraform mattermost-vnet: mattermost_lb_pip_name (has FQDN for CNAME)
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "chrisfickess-tfstate-azk"
    service.beta.kubernetes.io/azure-pip-name: "mattermost-dev-chris-mattermost-pip"
spec:
  type: LoadBalancer
  selector:
    app: mattermost
    installation.mattermost.com/installation: mattermost
    installation.mattermost.com/resource: mattermost
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8065
