apiVersion: v1
kind: Service
metadata:
  name: mattermost-lb
  namespace: mattermost
  annotations:
    # Optional: use if you have a static public IP pre-allocated
    # service.beta.kubernetes.io/azure-load-balancer-resource-group: "<resource-group-with-pip>"
    # service.beta.kubernetes.io/azure-pip-name: "<public-ip-name>"
spec:
  type: LoadBalancer
  selector:
    app: mattermost
    installation.mattermost.com/installation: mattermost
    installation.mattermost.com/resource: mattermost
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8065
